steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west6-docker.pkg.dev/$PROJECT_ID/sbb-chat/sbb-chat-mcp:$COMMIT_SHA'
      - '-t'
      - 'europe-west6-docker.pkg.dev/$PROJECT_ID/sbb-chat/sbb-chat-mcp:latest'
      - '.'
    
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west6-docker.pkg.dev/$PROJECT_ID/sbb-chat/sbb-chat-mcp'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sbb-chat-mcp'
      - '--image'
      - 'europe-west6-docker.pkg.dev/$PROJECT_ID/sbb-chat/sbb-chat-mcp:$COMMIT_SHA'
      - '--region'
      - 'europe-west6'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'GEMINI_API_KEY=gemini-api-key:latest,MCP_SERVER_URL=mcp-server-url:latest'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'

images:
  - 'europe-west6-docker.pkg.dev/$PROJECT_ID/sbb-chat/sbb-chat-mcp:$COMMIT_SHA'
  - 'europe-west6-docker.pkg.dev/$PROJECT_ID/sbb-chat/sbb-chat-mcp:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
